name: flutter_lol_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+10101

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/item.json
    - assets/champion/
    - assets/item/
